
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiamltIiwiaWF0IjoxNzAwNDk0MzM0LCJleHAiOjE3MDA0OTQzNDl9.jdAz54rOE6ULBgXxOqD5k2iFDWTP7b76V9LX9V2y04Y
#####

Post http://localhost:4000/token
Content-Type: application/json

{
    "token":
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiamltIiwiaWF0IjoxNzAwNDk0MjU0fQ.-wxQXEwJt8PwZt38bb_vl1fHwJH076T6UZBSHSMLmQA"
}



#####
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "jim"
}